Feature favorite novels
SBootCamp/visual_novel pull request #2
Opened 2022-06-16 17:19 UTC by ItMerser

2022-06-16 17:38 UTC, dolamroth requested changes

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/chart/views.py
> +    try:
```
visual_novel = ChartItem.objects.get(visual_novel__title=vn_title)
user_to_chart_item, _ = ChartItemToUser.objects.get_or_create(user_id=request.user.id, visual_novel=visual_novel)
```

И всё. Строчка `user.chart_item.add(new_vn)` не нужна, т.к. ты уже напрямую обращаешься к m2m-модели ChartItemToUser

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/chart/views.py
> +    user = ChartItemToUser.objects.get(user_id__id=request.user.id)
```
ChartItemToUser.objects.filter(user_id=request.user.id, visual_novel__title=vn_title).delete()
```

и всё

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/chart/views.py
> +    favorites_charts = [chart.visual_novel for chart in favorites_charts.chart_item.all()]
Раз ты в цикле вызываешь объект по "ленивой" связке (через ForeignKey), то в запросе необходимо заранее его подгрузить, чтобы избежать проблему N+1 запроса

https://scoutapm.com/blog/django-and-the-n1-queries-problem

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/chart/views.py
> +        favorites_charts = ChartItemToUser.objects.get(user__id=request.user.id)
Используй get_or_create

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/chart/views.py
> +        all_chart_items = all_chart_items.filter(visual_novel__in=favorites_charts)
Продвинутое, необязательно:

Весь этот запрос можно более эффективно построить, не вычисляя отдельно favorites_charts

```
favorites_subquery = ChartItemToUser.objects.filter(user=request.user, visual_novel_id=OuterRef('id')) # это ленивый запрос, он ещё не вычислен
all_chart_items = all_chart_items.filter(Exists(favorites_subquery))
```

документация
https://docs.djangoproject.com/en/4.0/ref/models/expressions/#exists-subqueries

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/chart/views.py
> +    if additional_breadcumb == 'Избранное':
Неясно назначение этого блока. Если у тебя рендеринг страницы "Избранное", то в queryset добавляешь соответствующий фильтр. Вручную из вычисленного множества ничего удалять не надо.

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/chart/views.py
> +        print(chart_item.get('title'))
Все дебажеские принты в мерж-реквесте нужно убирать

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/config/celery.py
> +app = Celery('config')
Для чего?

2022-06-16 17:38 UTC, dolamroth commented on visual_novel/templates/includes/site_map.html
> +    <li><a href="{% url 'chart_favorites' %}">Чарт избранных новелл</a></li>
Просто "Избранное"

2022-06-17 07:49 UTC, ItMerser commented on visual_novel/chart/views.py
> +    user = ChartItemToUser.objects.get(user_id__id=request.user.id)
Тут он будет удалять все вн пользователя сразу

2022-06-17 07:49 UTC, ItMerser commented on visual_novel/chart/views.py
> +    try:
И он не может так создать запись в поле m2m

2022-06-17 12:40 UTC, dolamroth requested changes

2022-06-17 12:40 UTC, dolamroth commented on visual_novel/chart/admin.py
> +class ChartItemToUserAdmin(admin.ModelAdmin):
В ChartItemAdmin добавь вывод инлайна с моделью ChartItemToUser

2022-06-17 12:40 UTC, dolamroth commented on visual_novel/chart/models.py
> +        verbose_name_plural = 'Избранные новеллы'
добавь uniqueconstraint на поля [user, chart_item]

https://docs.djangoproject.com/en/4.0/ref/models/constraints/#uniqueconstraint

2022-06-17 12:40 UTC, dolamroth commented on visual_novel/chart/views.py
> +    return HttpResponseRedirect('/chart/favorites')
доставай пути для редиректа из requests

2022-06-17 12:40 UTC, dolamroth commented on visual_novel/chart/views.py
> +    return HttpResponseRedirect('/chart')
доставай пути для редиректа из requests

2022-06-17 12:40 UTC, dolamroth commented on visual_novel/templates/chart/index.html
> +                                    <a href="{% url 'chart:chart_favorites_remove' visual_novel.title %}" class="btn btn-xs btn-primary">Удалить <i class="glyphicon glyphicon-remove"></i></a>
Удалить из избранного

2022-06-17 12:40 UTC, dolamroth commented on visual_novel/templates/includes/site_map.html
> +    <li><a href="{% url 'chart_favorites' %}">Избранные</a></li>
Избранное

2022-06-18 19:53 UTC, merged